elasticsearch:
    image: elasticsearch:2.4.5
    ports:
        - "9200:9200"
        - "9300:9300"

kibana:
    image: kibana:4.6.4
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
        - "5601:5601"
    links:
       - elasticsearch

